version: "3"
services:
  app:
    image: "node:10"
    container_name: "twitter_app"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./:/project"
    working_dir: "/project"
    command: "bash"
    tty: true
